#' Specify movement type
#' 
#' The generate_NAA_where() function is used to generate an array (n_stocks,n_regions,n_ages) 
#' which determines whether or not (T/F) the stock from a certain age can be present in a specific region.
#' 
#' @param basic_info Information generated by \code{\link{generate_basic_info}}
#' @param move.type Movement type:
#'   \itemize{
#'     \item \code{1} single stock movement (i.e. only stock 1 can move), with region-specific movement rates
#'     \item \code{2} bidirectional movement (i.e. all stocks can move), with region-specific movement rates (default)
#'     \item \code{3} no movement
#'     }
#'     
#' @return A list of information that will be used to prepare wham input
#'
#' @export
#'
#' @seealso \code{\link{prepare_wham_input}} and \code{\link{generate_move}}
#' 
#' @examples
#' \dontrun{
#' basic_info <- generate_basic_info()
#' basic_info <- generate_NAA_where(basic_info = basic_info, move.type = 2)
#' }
#' 
generate_NAA_where <- function(basic_info = basic_info, 
                               move.type = 2) {
  
  n_stocks = basic_info$n_stocks
  n_regions = basic_info$n_regions
  n_ages = basic_info$n_ages
  
  if (n_stocks == 1 & n_regions == 1) basic_info$NAA_where = array(1,dim = c(n_stocks,n_regions,n_ages))
  
  if (n_stocks > 1) {
    basic_info$NAA_where <- array(1, dim = c(n_stocks,n_regions,n_ages))
    if (move.type == 1) {
      basic_info$NAA_where[1,2:n_stocks,1] = 0
      basic_info$NAA_where[2:n_stocks,1,] = 0
    }
    if (move.type == 2) {
      basic_info$NAA_where[!diag(nrow(basic_info$NAA_where))] = 0
      basic_info$NAA_where[,,2:n_ages] = 1
    }
    if (move.type == 3) {
      basic_info$NAA_where[!diag(nrow(basic_info$NAA_where))] = 0
    }
  }
  
  return(basic_info)
}
